#!/usr/bin/env bash
#install nginx

#install nginx if it was not found
if ! which nginx;then
	# Update package list and install nginx
	apt-get update
	apt-get -y install nginx

	#Set up server block to return "Hello World!" for path '/'
	#Set up server block to return "301 Moved Permanently" rediraction for path '/redirect_me'
	cat <<'END' > /etc/nginx/sites-available/default
	##
	# You should look at the following URL's in order to grasp a solid understanding
	# of Nginx configuration files in order to fully unleash the power of Nginx.
	# https://www.nginx.com/resources/wiki/start/
	# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
	# https://wiki.debian.org/Nginx/DirectoryStructure
	#
	# In most cases, administrators will remove this file from sites-enabled/ and
	# leave it as reference inside of sites-available where it will continue to be
	# updated by the nginx packaging team.
	#
	# This file will automatically load configuration files provided by other
	# applications, such as Drupal or Wordpress. These applications will be made
	# available underneath a path with that package name, such as /drupal8.
	#
	# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
	##

	# Default server configuration
	#
	server {
			listen 80 default_server;
			listen [::]:80 default_server;

			# SSL configuration
			#
			# listen 443 ssl default_server;
			# listen [::]:443 ssl default_server;
			#
			# Note: You should disable gzip for SSL traffic.
			# See: https://bugs.debian.org/773332
			#
			# Read up on ssl_ciphers to ensure a secure configuration.
			# See: https://bugs.debian.org/765782
			#
			# Self signed certs generated by the ssl-cert package
			# Don't use them in a production server!
			#
			# include snippets/snakeoil.conf;

			root /var/www/html;

			# Add index.php to the list if you are using PHP
			index index.html index.htm index.nginx-debian.html;

			server_name _;

			location / {
					# First attempt to serve request as file, then
					# as directory, then fall back to displaying a 404.
					try_files $uri $uri/ =404;
			}
			
			#replace_with_sed

			# pass PHP scripts to FastCGI server
			#
			#location ~ \.php$ {
			#       include snippets/fastcgi-php.conf;
			#
			#       # With php-fpm (or other unix sockets):
			#       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
			#       # With php-cgi (or other tcp sockets):
			#       fastcgi_pass 127.0.0.1:9000;
			#}

			# deny access to .htaccess files, if Apache's document root
			# concurs with nginx's one
			#
			#location ~ /\.ht {
			#       deny all;
			#}
	}


	# Virtual Host configuration for example.com
	#
	# You can move that to a different file under sites-available/ and symlink that
	# to sites-enabled/ to enable it.
	#
	#server {
	#       listen 80;
	#       listen [::]:80;
	#
	#       server_name example.com;
	#
	#       root /var/www/example.com;
	#       index index.html;
	#
	#       location / {
	#               try_files $uri $uri/ =404;
	#       }
	#}
END

	# /redirect_me redirection and default 404 page
	echo "Hello World!" > index.nginx-debian.html
	echo "Ceci n'est pas une page" > /var/www/html/404.html
	sed -i "s]#replace_with_sed]location /redirect_me {\n\t\treturn 301 https://quickref.me/bash;\n\t}\
	\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}]" /etc/nginx/sites-available/default
	sed -i "s#^server {#add_header X-Served-By \$hostname;\nserver {#" /etc/nginx/sites-available/default

	# Restart nginx
	service nginx restart
fi

mkdir -p /data/ /data/web_static /data/web_static/releases /data/web_static/shared
mkdir -p /data/web_static/releases/test
echo "Holberton School" > /data/web_static/releases/test/index.html
if [[ -e /data/web_static/current ]];then
	rm /data/web_static/current
fi
ln -s /data/web_static/releases/test /data/web_static/current
chown -R ubuntu:ubuntu /data
sed -i "s#location /redirect_me {#location /hbnb_static {\n\t\talias /data/web_static/current/;\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n\n\tlocation /redirect_me {#" /etc/nginx/sites-available/default
service nginx restart
exit 0
